name: Build AOT Tool Packages

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.100-preview.6.25317.108'

jobs:
  build-platform-specific:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            rid: linux-x64
          - os: ubuntu-24.04-arm
            rid: linux-arm64
          - os: windows-2025
            rid: win-x64
          - os: macos-15
            rid: osx-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build AOT package for ${{ matrix.rid }}
      run: dotnet pack toolsay/toolsay.csproj -p:ToolType=aot -r ${{ matrix.rid }}

    - name: Upload platform-specific package
      uses: actions/upload-artifact@v4
      with:
        name: aot-package-${{ matrix.rid }}
        path: artifacts/packages/release/*.nupkg
        retention-days: 30
        if-no-files-found: error

  build-agnostic:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build agnostic AOT package
      run: dotnet pack toolsay/toolsay.csproj -p:ToolType=aot

    - name: Upload agnostic package
      uses: actions/upload-artifact@v4
      with:
        name: aot-package-agnostic
        path: artifacts/packages/release/*.nupkg
        retention-days: 30
        if-no-files-found: error

  collect-all-packages:
    needs: [build-platform-specific, build-agnostic]
    runs-on: ubuntu-latest

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: collected-packages

    - name: List all collected packages
      run: |
        echo "All collected AOT packages:"
        find collected-packages -name "*.nupkg" -type f | sort
        echo ""
        echo "Package count: $(find collected-packages -name "*.nupkg" -type f | wc -l)"

    - name: Upload all packages as single artifact
      uses: actions/upload-artifact@v4
      with:
        name: all-aot-packages
        path: collected-packages/**/*.nupkg
        retention-days: 90
        if-no-files-found: error
